# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def main_pods
    pod 'SwiftyJSON', '4.2.0'
    pod 'Alamofire', '4.7.3'
    pod 'ObjectMapper' ,'3.3.0'
    pod 'SDWebImage', '4.4.2'
    pod 'SkeletonView'
    pod 'RealmSwift'
    pod 'SnapKit'
    pod 'Toast-Swift'
    pod 'ReachabilitySwift'
end

target 'Crypto_Currency_Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  main_pods
  # Pods for Crypto_Currency_Wallet

  target 'Crypto_Currency_WalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crypto_Currency_WalletUITests' do
    # Pods for testing
  end

end
