//
//  HomeProtocols.swift
//  Crypto_Currency_Wallet
//
//  Created Tien Dinh on 11/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {

    var interactor: HomeInteractorInputProtocol? { get set }
    
    func getListCoin()
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: AnyObject {

    /* Interactor -> Presenter */
    func didGetListCoin(result: [CoinEntity]?, error: APIError?)
}

protocol HomeInteractorInputProtocol: AnyObject {

    var presenter: HomeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getListCoin()
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {

    var presenter: HomePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetListCoin(result: [CoinEntity]?, error: APIError?)
}
