//
//  HomePresenter.swift
//  Crypto_Currency_Wallet
//
//  Created Tien Dinh on 11/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class HomePresenter: HomePresenterProtocol {
    func getListCoin() {
        interactor?.getListCoin()
    }
    

    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorInputProtocol?
    private let router: HomeWireframeProtocol

    init(interface: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension HomePresenter: HomeInteractorOutputProtocol {
    func didGetListCoin(result: [CoinEntity]?, error: APIError?) {
        view?.didGetListCoin(result: result, error: error)
    }
}
