//
//  HomeProtocols.swift
//  Crypto_Currency_Wallet
//
//  Created Tien Dinh on 11/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Tien Dinh

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    
    var listCoin: [CoinEntity] { get set }
    var count: Int { get }
    var pageType: PageType { get set }
    var searchText: String { get set }
    var showSkeleton: Bool { get }

    var interactor: HomeInteractorInputProtocol? { get set }
    
    func getListCoinRepeat(_ time: Double)
    func coin(atIndex indexPath: IndexPath) -> CoinEntity?
    func filterDataType(_ type: PageType)
    func filterDataTypeText(_ text: String)
    func removeCoin(atIndex indexPath: IndexPath)
}

//MARK: Interactor -
protocol HomeInteractorOutputProtocol: AnyObject {

    /* Interactor -> Presenter */
    func didGetListCoin(result: [CoinEntity])
    func didGetListCoinError(error: APIError)
}

protocol HomeInteractorInputProtocol: AnyObject {

    var presenter: HomeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getListCoin()
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {

    var presenter: HomePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func reloadData()
}
